#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json
from pathlib import Path

EXTRA = []

def w(word, ipa, pos, tr, ex, exRu, bucket="object", note="", colloc=""):
    EXTRA.append({
        "word": word, "ipa": ipa, "pos": pos, "tr": tr,
        "ex": ex, "exRu": exRu, "bucket": bucket, "note": note, "colloc": colloc
    })

phrases = [
("as soon as", "/əz ˈsuːn əz/", "phrase", "как только", "Call me as soon as you arrive.", "Позвони, как только приедешь.", "time", "as soon as possible"),
("at least", "/ət ˈliːst/", "phrase", "по крайней мере", "Wait at least ten minutes.", "Подожди по крайней мере десять минут.", "number", ""),
("at once", "/ət ˈwʌns/", "phrase", "сразу", "Come here at once.", "Иди сюда сразу.", "time", ""),
("by the way", "/baɪ ðə ˈweɪ/", "phrase", "кстати", "By the way, are you free?", "Кстати, ты свободен?", "speech", ""),
("for example", "/fər ɪɡˈzæmpəl/", "phrase", "например", "Eat fruit, for example apples.", "Ешь фрукты, например яблоки.", "speech", ""),
("in fact", "/ɪn ˈfækt/", "phrase", "на самом деле", "In fact, I agree with you.", "На самом деле я с тобой согласен.", "speech", ""),
("in order to", "/ɪn ˈɔːrdər tuː/", "phrase", "для того чтобы", "I study in order to improve.", "Я учусь, чтобы улучшиться.", "idea", ""),
("instead of", "/ɪnˈstɛd əv/", "phrase", "вместо", "Walk instead of driving.", "Иди пешком вместо вождения.", "idea", ""),
("look forward to", "/lʊk ˈfɔːrwərd tuː/", "phrase", "ждать с нетерпением", "I look forward to meeting you.", "С нетерпением жду встречи.", "emotion", "look forward to doing"),
("make sure", "/meɪk ˈʃʊr/", "phrase", "убедиться", "Make sure the door is locked.", "Убедись, что дверь заперта.", "idea", ""),
("no longer", "/noʊ ˈlɔːŋɡər/", "phrase", "больше не", "She no longer lives here.", "Она больше здесь не живёт.", "time", ""),
("on purpose", "/ɑːn ˈpɜːrpəs/", "phrase", "нарочно", "I did not do it on purpose.", "Я сделал это не нарочно.", "idea", ""),
("once again", "/wʌns əˈɡɛn/", "phrase", "ещё раз", "Try once again carefully.", "Попробуй ещё раз осторожно.", "time", ""),
("out of order", "/aʊt əv ˈɔːrdər/", "phrase", "не работает", "The elevator is out of order.", "Лифт не работает.", "tech", ""),
("right away", "/raɪt əˈweɪ/", "phrase", "немедленно", "I will call right away.", "Я позвоню немедленно.", "time", ""),
("so far", "/soʊ ˈfɑːr/", "phrase", "до сих пор", "So far everything is fine.", "До сих пор всё хорошо.", "time", ""),
("take care", "/teɪk ˈkɛr/", "phrase", "береги себя", "Take care and write soon.", "Береги себя и пиши скорее.", "speech", ""),
("take place", "/teɪk ˈpleɪs/", "phrase", "происходить", "The meeting takes place tomorrow.", "Встреча происходит завтра.", "time", ""),
("used to", "/ˈjuːst tuː/", "phrase", "раньше делал", "I used to live in Chicago.", "Я раньше жил в Чикаго.", "time", "used to do"),
("according to", "/əˈkɔːrdɪŋ tuː/", "phrase", "согласно", "According to the map, turn left.", "Согласно карте, поверни налево.", "idea", ""),
("as well as", "/əz ˈwɛl əz/", "phrase", "а также", "She speaks English as well as French.", "Она говорит по-английски, а также по-французски.", "speech", ""),
("because of", "/bɪˈkɔːz əv/", "phrase", "из-за", "We stayed because of the rain.", "Мы остались из-за дождя.", "idea", ""),
("even though", "/ˈiːvən ðoʊ/", "phrase", "хотя", "Even though it rained, we walked.", "Хотя шёл дождь, мы гуляли.", "idea", ""),
("in case", "/ɪn ˈkeɪs/", "phrase", "на случай", "Take a coat in case it rains.", "Возьми пальто на случай дождя.", "idea", ""),
("in front of", "/ɪn ˈfrʌnt əv/", "phrase", "перед", "Wait in front of the shop.", "Жди перед магазином.", "place", ""),
("next to", "/ˈnɛkst tuː/", "phrase", "рядом с", "Sit next to me.", "Сядь рядом со мной.", "place", ""),
("thanks to", "/ˈθæŋks tuː/", "phrase", "благодаря", "Thanks to you, we finished.", "Благодаря тебе мы закончили.", "speech", ""),
("up to", "/ˈʌp tuː/", "phrase", "до", "It costs up to fifty dollars.", "Это стоит до пятидесяти долларов.", "money", ""),
("as long as", "/əz ˈlɔːŋ əz/", "phrase", "пока", "Stay as long as you need.", "Оставайся, пока нужно.", "time", ""),
("get rid of", "/ɡɛt ˈrɪd əv/", "phrase", "избавиться", "Get rid of old papers.", "Избавься от старых бумаг.", "action", ""),
("give up", "/ɡɪv ˈʌp/", "phrase", "сдаваться", "Do not give up now.", "Не сдавайся сейчас.", "emotion", ""),
("hang out", "/ˈhæŋ aʊt/", "phrase", "проводить время", "We hang out on weekends.", "Мы проводим время по выходным.", "person", ""),
("pick up", "/ˈpɪk ʌp/", "phrase", "забирать", "Pick up the kids at three.", "Забери детей в три.", "action", ""),
("put off", "/ˈpʊt ɔːf/", "phrase", "откладывать", "Do not put off studying.", "Не откладывай учёбу.", "time", ""),
("run out of", "/ˈrʌn aʊt əv/", "phrase", "закончиться", "We ran out of milk.", "У нас закончилось молоко.", "food", ""),
("set up", "/ˈsɛt ʌp/", "phrase", "настраивать", "Set up the new laptop.", "Настрой новый ноутбук.", "tech", ""),
("turn down", "/ˈtɜːrn daʊn/", "phrase", "отклонять", "They turned down my offer.", "Они отклонили моё предложение.", "work", ""),
("turn up", "/ˈtɜːrn ʌp/", "phrase", "появиться", "He turned up late.", "Он появился поздно.", "time", ""),
("work out", "/ˈwɜːrk aʊt/", "phrase", "тренироваться", "I work out three times weekly.", "Я тренируюсь три раза в неделю.", "sport", ""),
("find out", "/ˈfaɪnd aʊt/", "phrase", "выяснять", "Find out the train times.", "Выясни расписание поездов.", "idea", ""),
]
for word, ipa, pos, tr, ex, exRu, bucket, colloc in phrases:
    w(word, ipa, pos, tr, ex, exRu, bucket, "", colloc)

adverbs = [
("absolutely", "/ˈæbsəluːtli/", "абсолютно", "I absolutely agree.", "Я абсолютно согласен.", "speech"),
("afterwards", "/ˈæftərwərdz/", "после этого", "We ate and left afterwards.", "Мы поели и после этого ушли.", "time"),
("anyway", "/ˈɛniweɪ/", "в любом случае", "Anyway, let's continue.", "В любом случае, продолжим.", "speech"),
("approximately", "/əˈprɑːksɪmətli/", "приблизительно", "It takes approximately an hour.", "Это занимает приблизительно час.", "number"),
("basically", "/ˈbeɪsɪkli/", "в основном", "Basically, the plan works.", "В основном план работает.", "idea"),
("carefully", "/ˈkɛrfəli/", "осторожно", "Drive carefully in the rain.", "Езжай осторожно под дождём.", "action"),
("clearly", "/ˈklɪrli/", "ясно", "Speak clearly into the mic.", "Говори ясно в микрофон.", "speech"),
("completely", "/kəmˈpliːtli/", "полностью", "I completely understand.", "Я полностью понимаю.", "idea"),
("constantly", "/ˈkɑːnstəntli/", "постоянно", "She constantly checks her phone.", "Она постоянно проверяет телефон.", "time"),
("correctly", "/kəˈrɛktli/", "правильно", "Answer the question correctly.", "Ответь на вопрос правильно.", "school"),
("currently", "/ˈkɜːrəntli/", "сейчас", "I currently live downtown.", "Сейчас я живу в центре.", "time"),
("definitely", "/ˈdɛfənətli/", "определённо", "I will definitely come.", "Я определённо приду.", "speech"),
("directly", "/dəˈrɛktli/", "напрямую", "Go directly to the hotel.", "Иди напрямую в отель.", "travel"),
("easily", "/ˈiːzəli/", "легко", "She learns languages easily.", "Она легко учит языки.", "school"),
("elsewhere", "/ˈɛlswɛr/", "в другом месте", "Try searching elsewhere.", "Попробуй поискать в другом месте.", "place"),
("extremely", "/ɪkˈstriːmli/", "крайне", "It is extremely cold today.", "Сегодня крайне холодно.", "weather"),
("fairly", "/ˈfɛrli/", "довольно", "The test was fairly easy.", "Тест был довольно лёгким.", "idea"),
("fortunately", "/ˈfɔːrtʃənətli/", "к счастью", "Fortunately, nobody was hurt.", "К счастью, никто не пострадал.", "emotion"),
("frequently", "/ˈfriːkwəntli/", "часто", "I frequently work late.", "Я часто работаю допоздна.", "time"),
("fully", "/ˈfʊli/", "полностью", "I fully support the idea.", "Я полностью поддерживаю идею.", "idea"),
("generally", "/ˈdʒɛnərəli/", "обычно", "I generally wake early.", "Обычно я встаю рано.", "time"),
("gently", "/ˈdʒɛntli/", "нежно", "Close the door gently.", "Закрой дверь нежно.", "action"),
("gradually", "/ˈɡrædʒuəli/", "постепенно", "Prices rose gradually.", "Цены росли постепенно.", "time"),
("hardly", "/ˈhɑːrdli/", "едва", "I can hardly hear you.", "Я едва тебя слышу.", "speech"),
("highly", "/ˈhaɪli/", "весьма", "She is highly skilled.", "Она весьма квалифицирована.", "work"),
("honestly", "/ˈɑːnɪstli/", "честно", "Honestly, I do not know.", "Честно, я не знаю.", "speech"),
("increasingly", "/ɪnˈkriːsɪŋli/", "всё более", "Traffic is increasingly heavy.", "Движение всё более плотное.", "travel"),
("indeed", "/ɪnˈdiːd/", "действительно", "It was indeed a surprise.", "Это действительно был сюрприз.", "speech"),
("instead", "/ɪnˈstɛd/", "вместо этого", "Take the bus instead.", "Возьми автобус вместо этого.", "idea"),
("lately", "/ˈleɪtli/", "в последнее время", "I have been tired lately.", "В последнее время я устал.", "time"),
("mainly", "/ˈmeɪnli/", "главным образом", "I mainly work from home.", "Я главным образом работаю из дома.", "work"),
("nearly", "/ˈnɪrli/", "почти", "I nearly missed the train.", "Я почти опоздал на поезд.", "time"),
("normally", "/ˈnɔːrməli/", "обычно", "I normally eat breakfast.", "Обычно я завтракаю.", "time"),
("obviously", "/ˈɑːbviəsli/", "очевидно", "Obviously, we need more time.", "Очевидно, нам нужно больше времени.", "idea"),
("otherwise", "/ˈʌðərwaɪz/", "иначе", "Hurry, otherwise we will be late.", "Торопись, иначе опоздаем.", "idea"),
("particularly", "/pərˈtɪkjələrli/", "особенно", "I particularly enjoy jazz.", "Я особенно люблю джаз.", "emotion"),
("partly", "/ˈpɑːrtli/", "частично", "The museum is partly closed.", "Музей частично закрыт.", "place"),
("perfectly", "/ˈpɜːrfɪktli/", "идеально", "The plan worked perfectly.", "План сработал идеально.", "idea"),
("personally", "/ˈpɜːrsənəli/", "лично", "Personally, I disagree.", "Лично я не согласен.", "speech"),
("possibly", "/ˈpɑːsəbli/", "возможно", "It will possibly rain.", "Возможно, будет дождь.", "weather"),
("previously", "/ˈpriːviəsli/", "ранее", "I previously worked there.", "Ранее я там работал.", "time"),
("properly", "/ˈprɑːpərli/", "как следует", "Fix it properly this time.", "Почини это как следует.", "action"),
("quietly", "/ˈkwaɪətli/", "тихо", "Speak quietly in the library.", "Говори тихо в библиотеке.", "speech"),
("rarely", "/ˈrɛrli/", "редко", "I rarely eat fast food.", "Я редко ем фастфуд.", "time"),
("regularly", "/ˈrɛɡjələrli/", "регулярно", "Exercise regularly for health.", "Занимайся спортом регулярно.", "sport"),
("relatively", "/ˈrɛlətɪvli/", "относительно", "The hotel is relatively cheap.", "Отель относительно дешёвый.", "money"),
("seriously", "/ˈsɪriəsli/", "серьёзно", "Take safety seriously.", "Относись к безопасности серьёзно.", "idea"),
("significantly", "/sɪɡˈnɪfɪkəntli/", "значительно", "Costs rose significantly.", "Затраты значительно выросли.", "money"),
("simply", "/ˈsɪmpli/", "просто", "Simply press the button.", "Просто нажми кнопку.", "tech"),
("slightly", "/ˈslaɪtli/", "слегка", "The soup is slightly salty.", "Суп слегка солёный.", "food"),
("softly", "/ˈsɔːftli/", "мягко", "She spoke softly to the baby.", "Она мягко говорила с малышом.", "speech"),
("somehow", "/ˈsʌmhaʊ/", "как-то", "We somehow finished on time.", "Мы как-то закончили вовремя.", "idea"),
("specifically", "/spəˈsɪfɪkli/", "конкретно", "I specifically asked for tea.", "Я конкретно просил чай.", "speech"),
("surely", "/ˈʃʊrli/", "наверняка", "Surely you remember her.", "Наверняка ты её помнишь.", "idea"),
("therefore", "/ˈðɛrfɔːr/", "поэтому", "It rained; therefore we stayed.", "Шёл дождь; поэтому мы остались.", "idea"),
("thoroughly", "/ˈθɜːroʊli/", "тщательно", "Clean the kitchen thoroughly.", "Тщательно убери кухню.", "home"),
("totally", "/ˈtoʊtəli/", "полностью", "I totally agree with you.", "Я полностью с тобой согласен.", "speech"),
("typically", "/ˈtɪpɪkli/", "обычно", "I typically wake at seven.", "Обычно я встаю в семь.", "time"),
("unfortunately", "/ʌnˈfɔːrtʃənətli/", "к сожалению", "Unfortunately, tickets are sold out.", "К сожалению, билеты распроданы.", "emotion"),
("widely", "/ˈwaɪdli/", "широко", "The news spread widely.", "Новость широко распространилась.", "speech"),
]
for word, ipa, tr, ex, exRu, bucket in adverbs:
    w(word, ipa, "adv", tr, ex, exRu, bucket, "", "")

nouns = [
("menu", "/ˈmɛnjuː/", "меню", "Ask for the lunch menu.", "Попроси обеденное меню.", "food", "lunch menu"),
("method", "/ˈmɛθəd/", "метод", "Try a different method.", "Попробуй другой метод.", "idea", "teaching method"),
("microwave", "/ˈmaɪkrəweɪv/", "микроволновка", "Heat soup in the microwave.", "Разогрей суп в микроволновке.", "home", "microwave oven"),
("miracle", "/ˈmɪrəkəl/", "чудо", "It felt like a miracle.", "Это было как чудо.", "emotion", ""),
("mission", "/ˈmɪʃən/", "миссия", "Complete the mission safely.", "Безопасно выполни миссию.", "idea", ""),
("mixture", "/ˈmɪkstʃər/", "смесь", "Stir the cake mixture.", "Размешай смесь для торта.", "food", ""),
("model", "/ˈmɑːdəl/", "модель", "This is the latest model.", "Это последняя модель.", "tech", "role model"),
("mosquito", "/məˈskiːtoʊ/", "комар", "A mosquito bit my arm.", "Комар укусил мне руку.", "animal", ""),
("motivation", "/ˌmoʊtɪˈveɪʃən/", "мотивация", "Find your motivation daily.", "Находи мотивацию ежедневно.", "emotion", ""),
("motorcycle", "/ˈmoʊtərsaɪkəl/", "мотоцикл", "He rides a motorcycle.", "Он ездит на мотоцикле.", "travel", ""),
("muscle", "/ˈmʌsəl/", "мышца", "Stretch your leg muscles.", "Растяни мышцы ног.", "body", ""),
("mushroom", "/ˈmʌʃruːm/", "гриб", "Add mushrooms to the pizza.", "Добавь грибы на пиццу.", "food", ""),
("napkin", "/ˈnæpkɪn/", "салфетка", "Put a napkin on your lap.", "Положи салфетку на колени.", "food", ""),
("nation", "/ˈneɪʃən/", "нация", "Every nation has traditions.", "У каждой нации есть традиции.", "idea", ""),
("navigation", "/ˌnævɪˈɡeɪʃən/", "навигация", "Use phone navigation carefully.", "Осторожно используй навигацию.", "travel", ""),
("neighborhood", "/ˈneɪbərhʊd/", "район", "Our neighborhood is quiet.", "Наш район тихий.", "city", ""),
("nephew", "/ˈnɛfjuː/", "племянник", "My nephew starts school soon.", "Племянник скоро идёт в школу.", "person", ""),
("niece", "/niːs/", "племянница", "My niece loves drawing.", "Племянница любит рисовать.", "person", ""),
("nightmare", "/ˈnaɪtmɛr/", "кошмар", "I had a strange nightmare.", "Мне приснился странный кошмар.", "emotion", ""),
("nonsense", "/ˈnɑːnsɛns/", "чепуха", "Stop talking nonsense.", "Хватит говорить чепуху.", "speech", ""),
("novel", "/ˈnɑːvəl/", "роман", "I am reading a long novel.", "Я читаю длинный роман.", "school", ""),
("occupation", "/ˌɑːkjəˈpeɪʃən/", "профессия", "What is your occupation?", "Какая у тебя профессия?", "work", ""),
("operation", "/ˌɑːpəˈreɪʃən/", "операция", "The operation was successful.", "Операция прошла успешно.", "body", ""),
("opportunity", "/ˌɑːpərˈtuːnəti/", "возможность", "Take this opportunity seriously.", "Отнесись к этой возможности серьёзно.", "idea", ""),
("option", "/ˈɑːpʃən/", "вариант", "Choose the best option.", "Выбери лучший вариант.", "idea", ""),
("orchestra", "/ˈɔːrkɪstrə/", "оркестр", "The orchestra played beautifully.", "Оркестр играл прекрасно.", "idea", ""),
("organization", "/ˌɔːrɡənəˈzeɪʃən/", "организация", "Join a volunteer organization.", "Вступи в волонтёрскую организацию.", "work", ""),
("origin", "/ˈɔːrɪdʒɪn/", "происхождение", "What is the word origin?", "Каково происхождение слова?", "idea", ""),
("outcome", "/ˈaʊtkʌm/", "результат", "Wait for the final outcome.", "Жди конечного результата.", "idea", ""),
("outline", "/ˈaʊtlaɪn/", "план", "Write an essay outline first.", "Сначала напиши план эссе.", "school", ""),
("overcoat", "/ˈoʊvərkoʊt/", "пальто", "Wear a warm overcoat.", "Надень тёплое пальто.", "clothes", ""),
("owner", "/ˈoʊnər/", "владелец", "Ask the shop owner.", "Спроси владельца магазина.", "work", ""),
("package", "/ˈpækɪdʒ/", "посылка", "Collect your package today.", "Забери посылку сегодня.", "object", ""),
("painting", "/ˈpeɪntɪŋ/", "картина", "Hang the painting carefully.", "Осторожно повесь картину.", "object", ""),
("palace", "/ˈpæləs/", "дворец", "Tourists visit the palace.", "Туристы посещают дворец.", "place", ""),
("panic", "/ˈpænɪk/", "паника", "Do not panic in emergencies.", "Не паникуй в чрезвычайных ситуациях.", "emotion", ""),
("paragraph", "/ˈpærəɡræf/", "абзац", "Read the first paragraph.", "Прочитай первый абзац.", "school", ""),
("partner", "/ˈpɑːrtnər/", "партнёр", "Find a study partner.", "Найди партнёра для учёбы.", "person", ""),
("passenger", "/ˈpæsɪndʒər/", "пассажир", "Passengers must wear seatbelts.", "Пассажиры должны пристегиваться.", "travel", ""),
("path", "/pæθ/", "тропа", "Follow the forest path.", "Следуй по лесной тропе.", "nature", ""),
("patience", "/ˈpeɪʃəns/", "терпение", "Learning needs patience.", "Учёба требует терпения.", "emotion", ""),
("pattern", "/ˈpætərn/", "узор", "Notice the weather pattern.", "Заметь погодный узор.", "idea", ""),
("payment", "/ˈpeɪmənt/", "платёж", "Make the payment online.", "Сделай платёж онлайн.", "money", ""),
("peak", "/piːk/", "пик", "Reach the mountain peak.", "Достигни пика горы.", "nature", ""),
("penalty", "/ˈpɛnəlti/", "штраф", "Pay the parking penalty.", "Заплати штраф за парковку.", "money", ""),
("penguin", "/ˈpɛŋɡwɪn/", "пингвин", "Penguins live in cold places.", "Пингвины живут в холодных местах.", "animal", ""),
("performance", "/pərˈfɔːrməns/", "выступление", "Enjoy the evening performance.", "Наслаждайся вечерним выступлением.", "idea", ""),
("permission", "/pərˈmɪʃən/", "разрешение", "Ask permission before leaving.", "Попроси разрешение перед уходом.", "idea", ""),
("petrol", "/ˈpɛtrəl/", "бензин", "Fill the car with petrol.", "Залей бензин в машину.", "travel", ""),
("phrase", "/freɪz/", "фраза", "Learn useful phrases.", "Учи полезные фразы.", "speech", ""),
("pillow", "/ˈpɪloʊ/", "подушка", "Buy a soft pillow.", "Купи мягкую подушку.", "home", ""),
("pity", "/ˈpɪti/", "жалость", "What a pity you missed it.", "Как жаль, что ты это пропустил.", "emotion", ""),
("planet", "/ˈplænɪt/", "планета", "Earth is our planet.", "Земля — наша планета.", "nature", ""),
("platform", "/ˈplætfɔːrm/", "платформа", "Wait on platform three.", "Жди на платформе три.", "travel", ""),
("pleasure", "/ˈplɛʒər/", "удовольствие", "It is a pleasure to help.", "Помогать — удовольствие.", "emotion", ""),
("poem", "/ˈpoʊəm/", "стихотворение", "Write a short poem.", "Напиши короткое стихотворение.", "school", ""),
("poet", "/ˈpoʊət/", "поэт", "The poet read aloud.", "Поэт читал вслух.", "job", ""),
("poison", "/ˈpɔɪzən/", "яд", "Keep poison locked away.", "Храни яд под замком.", "object", ""),
("policy", "/ˈpɑːləsi/", "политика", "Read the company policy.", "Прочитай политику компании.", "work", ""),
("population", "/ˌpɑːpjəˈleɪʃən/", "население", "The population is growing.", "Население растёт.", "city", ""),
("position", "/pəˈzɪʃən/", "должность", "Apply for a new position.", "Подай заявку на новую должность.", "work", ""),
("possibility", "/ˌpɑːsəˈbɪləti/", "возможность", "There is a possibility of rain.", "Есть возможность дождя.", "idea", ""),
("poster", "/ˈpoʊstər/", "плакат", "Hang a movie poster.", "Повесь киноплакат.", "object", ""),
("poverty", "/ˈpɑːvərti/", "бедность", "Fight poverty with education.", "Борись с бедностью через образование.", "money", ""),
("powder", "/ˈpaʊdər/", "порошок", "Add baking powder carefully.", "Осторожно добавь разрыхлитель.", "food", ""),
("praise", "/preɪz/", "похвала", "Teachers give fair praise.", "Учителя дают справедливую похвалу.", "speech", ""),
("preference", "/ˈprɛfərəns/", "предпочтение", "State your food preference.", "Укажи пищевое предпочтение.", "idea", ""),
("preparation", "/ˌprɛpəˈreɪʃən/", "подготовка", "Exam preparation takes time.", "Подготовка к экзамену занимает время.", "school", ""),
("presence", "/ˈprɛzəns/", "присутствие", "Thank you for your presence.", "Спасибо за присутствие.", "person", ""),
("presentation", "/ˌprɛzənˈteɪʃən/", "презентация", "Prepare a short presentation.", "Подготовь короткую презентацию.", "work", ""),
("pressure", "/ˈprɛʃər/", "давление", "Work under pressure carefully.", "Осторожно работай под давлением.", "work", ""),
("prevention", "/prɪˈvɛnʃən/", "профилактика", "Prevention is better than cure.", "Профилактика лучше лечения.", "body", ""),
("pride", "/praɪd/", "гордость", "Take pride in your work.", "Гордись своей работой.", "emotion", ""),
("principle", "/ˈprɪnsəpəl/", "принцип", "Follow basic safety principles.", "Следуй основным принципам безопасности.", "idea", ""),
("priority", "/praɪˈɔːrəti/", "приоритет", "Health is my priority.", "Здоровье — мой приоритет.", "idea", ""),
("prison", "/ˈprɪzən/", "тюрьма", "He spent years in prison.", "Он провёл годы в тюрьме.", "place", ""),
("privacy", "/ˈpraɪvəsi/", "конфиденциальность", "Respect online privacy.", "Уважай онлайн-конфиденциальность.", "tech", ""),
("procedure", "/prəˈsiːdʒər/", "процедура", "Follow the safety procedure.", "Следуй процедуре безопасности.", "work", ""),
("process", "/ˈprɑːsɛs/", "процесс", "Explain the hiring process.", "Объясни процесс найма.", "work", ""),
("production", "/prəˈdʌkʃən/", "производство", "Car production increased.", "Производство машин выросло.", "work", ""),
("profession", "/prəˈfɛʃən/", "профессия", "Teaching is a noble profession.", "Преподавание — благородная профессия.", "work", ""),
("professor", "/prəˈfɛsər/", "профессор", "Ask the professor a question.", "Задай профессору вопрос.", "job", ""),
("profit", "/ˈprɑːfɪt/", "прибыль", "The shop made a profit.", "Магазин получил прибыль.", "money", ""),
("program", "/ˈproʊɡræm/", "программа", "Install the new program.", "Установи новую программу.", "tech", ""),
("progress", "/ˈprɑːɡrɛs/", "прогресс", "Show steady progress.", "Покажи устойчивый прогресс.", "school", ""),
("project", "/ˈprɑːdʒɛkt/", "проект", "Finish the group project.", "Закончи групповой проект.", "work", ""),
("promotion", "/prəˈmoʊʃən/", "повышение", "She got a promotion.", "Она получила повышение.", "work", ""),
("proof", "/pruːf/", "доказательство", "Show proof of purchase.", "Покажи доказательство покупки.", "idea", ""),
("property", "/ˈprɑːpərti/", "собственность", "Protect private property.", "Защищай частную собственность.", "home", ""),
("proposal", "/prəˈpoʊzəl/", "предложение", "Read the business proposal.", "Прочитай деловое предложение.", "work", ""),
("protection", "/prəˈtɛkʃən/", "защита", "Wear sun protection.", "Носи защиту от солнца.", "body", ""),
("protein", "/ˈproʊtiːn/", "белок", "Eggs provide protein.", "Яйца дают белок.", "food", ""),
("protest", "/ˈproʊtɛst/", "протест", "Join a peaceful protest.", "Участвуй в мирном протесте.", "idea", ""),
("province", "/ˈprɑːvɪns/", "провинция", "She lives in another province.", "Она живёт в другой провинции.", "place", ""),
("publication", "/ˌpʌblɪˈkeɪʃən/", "публикация", "Read the latest publication.", "Прочитай последнюю публикацию.", "work", ""),
("pudding", "/ˈpʊdɪŋ/", "пудинг", "Try the chocolate pudding.", "Попробуй шоколадный пудинг.", "food", ""),
("pulse", "/pʌls/", "пульс", "Check your pulse carefully.", "Осторожно проверь пульс.", "body", ""),
("pupil", "/ˈpjuːpəl/", "ученик", "Every pupil needs support.", "Каждому ученику нужна поддержка.", "school", ""),
("purpose", "/ˈpɜːrpəs/", "цель", "What is the purpose?", "Какова цель?", "idea", ""),
("purse", "/pɜːrs/", "дамская сумка", "She lost her purse.", "Она потеряла сумку.", "clothes", ""),
("puzzle", "/ˈpʌzəl/", "головоломка", "Solve the crossword puzzle.", "Реши кроссворд.", "idea", ""),
("quantity", "/ˈkwɑːntəti/", "количество", "Check the quantity carefully.", "Осторожно проверь количество.", "number", ""),
("quarter", "/ˈkwɔːrtər/", "четверть", "Wait a quarter of an hour.", "Подожди четверть часа.", "time", ""),
("questionnaire", "/ˌkwɛstʃəˈnɛr/", "анкета", "Fill in the questionnaire.", "Заполни анкету.", "work", ""),
("quote", "/kwoʊt/", "цитата", "Copy this famous quote.", "Скопируй эту известную цитату.", "speech", ""),
]
for word, ipa, tr, ex, exRu, bucket, colloc in nouns:
    w(word, ipa, "noun", tr, ex, exRu, bucket, "", colloc)

out = Path(__file__).resolve().parent / "a2_parts" / "extra.json"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(EXTRA, ensure_ascii=False), encoding="utf-8")
print("wrote", len(EXTRA), "extra rows")
